# Regenerates WinFormsShim\Keys.g.cs from the real System.Windows.Forms.Keys (run on Windows).
# Hotkeys are persisted by name/value, so the stand-in has to match WinForms exactly.
param(
    [string] $Output = (Join-Path $PSScriptRoot '..\WinFormsShim\Keys.g.cs')
)

Add-Type -AssemblyName System.Windows.Forms

$type = [System.Windows.Forms.Keys]
$lines = foreach ($name in [Enum]::GetNames($type)) {
    $value = [int][Enum]::Parse($type, $name)
    "    $name = $value,"
}

$source = @"
// <auto-generated>Generated by eng/Generate-KeysShim.ps1 from System.Windows.Forms.Keys. Do not edit.</auto-generated>
#pragma warning disable SA1600, SA1602, CS1591 // Generated

namespace System.Windows.Forms;

[Flags]
public enum Keys
{
$($lines -join [Environment]::NewLine)
}
"@

[IO.File]::WriteAllText($Output, $source, (New-Object Text.UTF8Encoding($false)))
"Wrote $(@($lines).Count) members to $Output"
